builds:
- env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  goos:
    - windows
    - darwin
    - linux
  goarch:
    - amd64
    - arm64
    - arm
  ignore:
    - goos: freebsd
      goarch: arm
      goarm: 6
    - goos: openbsd
      goarch: arm
      goarm: 6
archives:
-
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
  format_overrides:
    - goos: windows
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  commit_author:
    email: vbauerster@gmail.com
    name:  vbauerster
  description: "HTTP Download Manager with multi-parts"
  folder: Formula
  github:
    name:  homebrew-getparty
    owner: vbauerster
  homepage: "https://github.com/vbauerster/getparty"
  test: "system  \"#{bin}/getparty --version\""
